# CS 5408 - Game Theory for Computing

## Topic 0: Introduction -- Prerequisites 
\
COPYRIGHTS: © Sid Nadendla, 2021

### Things to Remember

* All programming assignments should be written in **Python 3.8+** and submitted as **Jupyter notebooks** in assigned **Gitlab** repositories before the submission deadline. 
    * All other submissions will be rejected -- in which case, zero points will be automatically awarded. 
    * Any exceptions can only be granted at the discretion of the instructor only under justifiable circumstances.
    
* To work on a Unix terminal from any Windows machine, you may use **PuTTY**, a free and open-source SSH/Telnet client, and follow the instructions in this [link](https://it.mst.edu/services/remote-desktop-connection/install-putty/) to gain access to our campus' standard Unix installation. 
    * If you are off-campus, you need to first connect to our campus VPN by following the instructions provided in this [link](https://it.mst.edu/services/vpn/).

* Note that the code provided by the instructor cannot be changed. You can only write your code in the blanks, as instructed by comments within respective code cells.

### Resources

* Official Python Documentation: [https://www.python.org/doc/](https://www.python.org/doc/)

* IBM's Markdown Cheatsheet for Jupyter Notebook: [https://www.ibm.com/docs/en/watson-studio-local/1.2.3?topic=notebooks-markdown-jupyter-cheatsheet](https://www.ibm.com/docs/en/watson-studio-local/1.2.3?topic=notebooks-markdown-jupyter-cheatsheet) \

* Git: [https://git-scm.com/doc](https://git-scm.com/doc)

### One-Time Setup Instructions

In Unix terminal, perform the following steps:

**STEP 1:** Make sure you have git, Python and any other necessary prerequisites installed in your workstation: \
`git --version` \
`python3 --version`

Then, check what the default Python version is, on your workstation: \
`python --version` \
If the default Python version is python2, then change it to Python 3, if it is already installed in your system: \
`alias python=python3`

**STEP 2:** Create a virtual environment: \
`python -m venv fs2021-cs5408-venv`

**STEP 3:** Activate the virtual environment: \
`source fs2021-cs5408-venv/bin/activate`

**STEP 4:** Install all the necessary dependencies within the virtual environment in the following order: \
`pip install --upgrade pip` \
`pip install git`
`pip install jupyter` \
`pip install gym` 

### Instructions for every submission

In order to work on your HWs and/or projects, perform the following steps:

STEP 1: Activate the virtual environment: \
`source fs2021-c5408-venv\bin\activate`

STEP 2: Clone the appropriate git repository: \
`git clone <git-repository-address>`

STEP 3: Open Jupyter Notebook: \
`jupyter notebook`

STEP 4: Once the notebook opens in your browser, update the code in existing Jupyter notebooks.  

STEP 5: Upon closing the Jupyter Notebook, run the following command in your terminal:
`pip freeze > requirements.txt`

STEP 6: Commit your code back to your respective git repositories after every new update:
`git commit `

### Example Code in Python

**Note:** Every notebook is independent, and therefore the code needs to be self-contained. 

In [4]:
# Install any necessary package other than the one listed in the one-time setup instructions

!pip install numpy # This package allows you to compute Nash equilibrium using Lemke-Howson algorithm.

     |████████████████████████████████| 16.9 MB 2.8 MB/s eta 0:00:01


In [5]:
# Import all necessary global packages

import numpy as np

#### 1. Different ways to represent numbers

In [6]:
var1 = 1000000
var2 = 1_000_000
var3 = 1e6

print(f"Is var1 = var2? : {var1==var2}")
print(f"Is var1 = var3? : {var1==var3}")

Is var1 = var2? : True
Is var1 = var3? : True


#### 2. Random number generation

In [13]:
x = np.random.uniform(0,1,5)
print(f"x = {x}")
print(f"x[0]*10^3 = {x[0]*(10**3)}")

x = [0.26007329 0.71185837 0.00198077 0.19316859 0.2287486 ]
x[0]*10^3 = 260.0732925778095


#### 3. Matrix Operations

In [33]:
M0 = np.zeros((2,3))
print(f"Matrix M0 = {M0} \n")

M1 = np.ones((5,2))
print(f"Matrix M1 = {M1} \n")

M2 = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]
print(f"M2 = {M2} \n")

# Printing the 2nd row in M2
print(f"M2[1] = {M2[1]} \n")

# Printing the 3rd element of 2nd row in M2
print(f"M2[1][2] = {M2[1][2]} \n")

# Printing the last element of 1st Row of M2
print(f"M2[0][-1] = {M2[0][-1]} \n") 

# Printing the second-to-last element of 3rd Row of M2
print(f"M2[2][-2] = {M2[2][-2]} \n") 

# Printing the 3rd column in M2
column = [];        # empty list
for row in M2:
  column.append(row[2])   
print(f"3rd column in M2 = {column} \n") 

# Deleting the second row in M2
M4 = np.delete(M2,1,axis=0)
print(f"M4 = {M4} \n")

# Deleting the third column in M2
M5 = np.delete(M2,2,axis=1)
print(f"M5 = {M5} \n")

Matrix M0 = [[0. 0. 0.]
 [0. 0. 0.]] 

Matrix M1 = [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

M2 = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]] 

M2[1] = [-5, 8, 9, 0] 

M2[1][2] = 9 

M2[0][-1] = 12 

M2[2][-2] = 11 

3rd column in M2 = [5, 9, 11] 

M4 = [[ 1  4  5 12]
 [-6  7 11 19]] 

M5 = [[ 1  4 12]
 [-5  8  0]
 [-6  7 19]] 

